build_script:
  - SET PATH=C:\Python38;C:\Python38\Scripts;%PATH%
  - python -m pip install --upgrade pip
  - pip install cibuildwheel==1.3.0
  - cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        python -m pip install twine
        python -m twine upload --skip-existing (resolve-path wheelhouse\*.whl)
      }
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
environment:
  CIBW_SKIP: "cp27-*"
